# Generated by Django 3.1.2 on 2020-10-17 13:40

import delivery.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('serial_pas_c', models.IntegerField()),
                ('number_pas_c', models.IntegerField()),
                ('first_name', models.CharField(max_length=20, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=20, verbose_name='Отчество')),
                ('address', models.CharField(max_length=50)),
                ('phone_num', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Order_product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(auto_now=True)),
                ('amount', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=20, null=True, verbose_name='Отчество')),
                ('post', models.CharField(max_length=20, verbose_name='Должность')),
                ('serial_pas', models.IntegerField()),
                ('num_pas', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
                ('phone_num', models.CharField(max_length=20, verbose_name='Номер телефона')),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacy_expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_e', models.CharField(choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], max_length=20)),
                ('year_e', models.IntegerField()),
                ('rent', models.IntegerField()),
                ('utilities', models.IntegerField()),
                ('advertising', models.IntegerField()),
                ('inner_expenses', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacy_income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_i', models.CharField(choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], max_length=20)),
                ('year_i', models.IntegerField()),
                ('personnel_income', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('artikul', models.IntegerField()),
                ('product_name', models.CharField(max_length=20)),
                ('composition', models.CharField(max_length=255)),
                ('cost_one', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('expiration_date', models.DateTimeField()),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('phone_num', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.IntegerField()),
                ('prize', models.IntegerField()),
                ('prepayment', models.IntegerField(null=True)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='delivery.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='Product_supply',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('supply_date', models.DateField(auto_now_add=True)),
                ('supply_time', models.TimeField(auto_now_add=True)),
                ('amount', models.IntegerField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='delivery.order_product')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='delivery.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='delivery.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Product_sale',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('count', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='delivery.product')),
            ],
        ),
        migrations.AddField(
            model_name='order_product',
            name='personnel_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.personnel'),
        ),
        migrations.AddField(
            model_name='order_product',
            name='product_name',
            field=models.ManyToManyField(to='delivery.Product'),
        ),
        migrations.CreateModel(
            name='Accounting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.ForeignKey(on_delete=delivery.models.Pharmacy_expense, to='delivery.pharmacy_income')),
            ],
        ),
    ]
