# Generated by Django 3.1.2 on 2020-10-20 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_product',
            old_name='product_name',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='product_supply',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='product_supply',
            old_name='product_name',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='order_product',
            name='personnel_id',
        ),
        migrations.AddField(
            model_name='order_product',
            name='personnel',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='delivery.personnel'),
        ),
        migrations.AddField(
            model_name='product_sale',
            name='personnel',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.DO_NOTHING, to='delivery.personnel'),
        ),
        migrations.AddField(
            model_name='product_supply',
            name='personnel',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.DO_NOTHING, to='delivery.personnel'),
        ),
        migrations.AlterField(
            model_name='pharmacy_expense',
            name='month_e',
            field=models.CharField(choices=[('JAN', 'January'), ('FEB', 'February'), ('MAR', 'March'), ('APR', 'April'), ('MAY', 'May'), ('JUN', 'June'), ('JUL', 'July'), ('AUG', 'August'), ('SEP', 'September'), ('OCT', 'October'), ('NOV', 'November'), ('DEC', 'December')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pharmacy_income',
            name='month_i',
            field=models.CharField(choices=[('JAN', 'January'), ('FEB', 'February'), ('MAR', 'March'), ('APR', 'April'), ('MAY', 'May'), ('JUN', 'June'), ('JUL', 'July'), ('AUG', 'August'), ('SEP', 'September'), ('OCT', 'October'), ('NOV', 'November'), ('DEC', 'December')], max_length=20),
        ),
    ]
