# Generated by Django 3.1.2 on 2020-10-26 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_order_product_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_product',
            name='price',
        ),
    ]
