# Generated by Django 3.1.2 on 2020-10-26 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_remove_order_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_supply',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product_supply',
            name='supplier',
        ),
    ]
