# Generated by Django 3.1.2 on 2020-10-26 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_auto_20201026_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
