# Generated by Django 3.1.2 on 2020-11-01 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_auto_20201026_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_product',
            name='product',
        ),
        migrations.AddField(
            model_name='order_product',
            name='product',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.DO_NOTHING, to='delivery.product'),
        ),
        migrations.AlterField(
            model_name='order_product',
            name='supplier',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.DO_NOTHING, to='delivery.supplier'),
        ),
    ]
