# Generated by Django 3.1.2 on 2020-11-03 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0012_auto_20201101_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_product',
            name='product',
            field=models.ForeignKey(db_constraint=False, default=False, on_delete=django.db.models.deletion.DO_NOTHING, to='delivery.product'),
        ),
    ]
