# Generated by Django 3.1.2 on 2020-11-04 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0014_auto_20201103_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='personnel',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='delivery.personnel'),
        ),
    ]
