# Generated by Django 3.1.2 on 2020-11-04 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0015_auto_20201105_0207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounting',
            name='date',
        ),
        migrations.AddField(
            model_name='accounting',
            name='month_e',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.DO_NOTHING, to='delivery.pharmacy_expense'),
        ),
        migrations.AddField(
            model_name='accounting',
            name='month_i',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.DO_NOTHING, to='delivery.pharmacy_income'),
        ),
    ]
