# Generated by Django 3.1.2 on 2020-12-09 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0016_auto_20201105_0325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_supply',
            old_name='amount',
            new_name='quantity',
        ),
    ]
