# Generated by Django 3.1.2 on 2020-12-09 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0017_auto_20201209_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='personnel',
            field=models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, to='delivery.personnel'),
        ),
    ]
