# Generated by Django 3.1.2 on 2020-12-09 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0018_auto_20201209_2230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pharmacy_expense',
            old_name='month_e',
            new_name='month',
        ),
        migrations.RenameField(
            model_name='pharmacy_expense',
            old_name='year_e',
            new_name='year',
        ),
        migrations.RenameField(
            model_name='pharmacy_income',
            old_name='month_i',
            new_name='month',
        ),
        migrations.RenameField(
            model_name='pharmacy_income',
            old_name='year_i',
            new_name='year',
        ),
        migrations.AlterField(
            model_name='accounting',
            name='month_e',
            field=models.OneToOneField(default=False, on_delete=django.db.models.deletion.DO_NOTHING, to='delivery.pharmacy_expense'),
        ),
        migrations.AlterField(
            model_name='accounting',
            name='month_i',
            field=models.OneToOneField(default=False, on_delete=django.db.models.deletion.DO_NOTHING, to='delivery.pharmacy_income'),
        ),
    ]
