# Generated by Django 3.1.2 on 2020-12-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0020_accounting_total_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounting',
            name='total_expense',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='accounting',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pharmacy_expense',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pharmacy_income',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
