# Generated by Django 3.1.2 on 2020-12-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0021_auto_20201209_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounting',
            name='total_expense',
        ),
        migrations.AddField(
            model_name='pharmacy_expense',
            name='total_expense',
            field=models.IntegerField(default=0),
        ),
    ]
